# Generated by Django 5.0.7 on 2024-07-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bicycle',
            options={'verbose_name': 'Bicycle', 'verbose_name_plural': 'Bicycles'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Rental', 'verbose_name_plural': 'Rentals'},
        ),
        migrations.AddField(
            model_name='rental',
            name='trip_price_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rental',
            name='datetime_rented_stop',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
